apiVersion: v2
name: grafana
description: Grafana visualization dashboard
type: application
version: 1.0.0
appVersion: 10.2.0
dependencies:
  - name: grafana
    version: 7.0.0
    repository: https://grafana.github.io/helm-charts
