apiVersion: v2
name: alertmanager
description: Prometheus Alertmanager
type: application
version: 1.0.0
appVersion: 0.26.0
dependencies:
  - name: alertmanager
    version: 1.7.0
    repository: https://prometheus-community.github.io/helm-charts
