apiVersion: v2
name: prometheus
description: Prometheus monitoring system
type: application
version: 1.0.0
appVersion: 2.48.0
dependencies:
  - name: prometheus
    version: 25.8.0
    repository: https://prometheus-community.github.io/helm-charts
